# Decision Layer Configuration

# Storage configuration
storage:
  backend: "postgresql"  # or "file"
  connection_string: "postgresql://decision_user:decision_password@postgres:5432/decision_layer"
  # For file storage:
  # backend: "file"
  # path: "./functions"

# Security configuration
security:
  enable_auth: true
  api_key: "${DECISION_LAYER_API_KEY}"  # Set via environment variable
  enable_rate_limiting: true
  enable_input_sanitization: true
  enable_trace_sanitization: true
  max_input_size: 1048576  # 1MB
  rate_limit_requests: 100
  rate_limit_window: 60

# Plugin configuration
plugins:
  validation:
    enabled: true
  tracing:
    enabled: true
    path: "./traces"
  caching:
    enabled: true

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  enable_docs: true
  enable_cors: true
