# Decision Layer Configuration

# Core system configuration
core:
  storage_backend: "postgresql"  # or "file"
  trace_dir: "./traces"
  max_input_size: 1048576  # 1MB
  log_level: "INFO"

# Storage configuration
storage:
  backend: "postgresql"  # or "file"
  connection_string: "postgresql://decision_user:${DB_PASSWORD:-decision_password}@postgres:5432/decision_layer"
  # For file storage:
  # backend: "file"
  # path: "./functions"

# Security configuration
security:
  enable_auth: true
  api_key: "${DECISION_LAYER_API_KEY}"  # Set via environment variable
  enable_rate_limiting: true
  enable_input_sanitization: true
  enable_trace_sanitization: true
  max_input_size: 1048576  # 1MB
  rate_limit_requests: 100
  rate_limit_window: 60

# Plugin configuration
plugins:
  validation:
    enabled: true
  tracing:
    enabled: true
    path: "./traces"
  caching:
    enabled: true

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  enable_docs: true
  enable_cors: true

# Cross-Domain Integration
integrations:
  llm:
    provider: mock  # or openai, anthropic
    config: {}
  ontology:
    provider: mock  # or owl, neo4j
    config: {}
  knowledge_graph:
    provider: mock  # or neo4j, amazon_neptune
    config: {}

# Development configuration
development:
  debug: false
  hot_reload: false
  profiling: false

# Production configuration
production:
  debug: false
  hot_reload: false
  profiling: false
  monitoring:
    enabled: true
    metrics_endpoint: "/metrics"
    health_endpoint: "/health"
