version: '3.8'

services:
  decision-layer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DECISION_LAYER_API_KEY=${DECISION_LAYER_API_KEY:-your-secret-api-key}
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - ./traces:/app/traces
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=decision_layer
      - POSTGRES_USER=decision_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-decision_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U decision_user -d decision_layer"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 