name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    # Single Python version for faster builds
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint and format check
        run: |
          python -m flake8 policy_as_code tests --extend-ignore=F401,F402,F841,E501,E203,E722,F824
          python -m black --check policy_as_code tests

      - name: Type check
        run: |
          python -m mypy policy_as_code --ignore-missing-imports

      - name: Test with pytest
        run: |
          python -m pytest tests/ -v --cov=policy_as_code --cov-report=xml --cov-fail-under=70
