name: Validate Metadata

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate-jsonld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install validator
        run: |
          pip install pyshacl rdflib jsonschema pyyaml
      - name: Validate Policy Metadata
        run: |
          python3 scripts/validate_policies_comprehensive.py
