name: Ontology Validation

on:
  push:
    branches: [main]
    paths:
      - "examples/policies/**"
      - "schemas/**"
      - "docs/ontology/**"
  pull_request:
    branches: [main]
    paths:
      - "examples/policies/**"
      - "schemas/**"
      - "docs/ontology/**"

jobs:
  validate-ontology:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install rdflib pyshacl pyyaml

      - name: Validate YAML to JSON-LD conversion
        run: |
          python scripts/yaml_to_jsonld.py examples/policies/healthcare_eligibility.yaml docs/ontology/context.jsonld > /tmp/test.jsonld
          python -c "
          import json
          with open('/tmp/test.jsonld', 'r') as f:
              data = json.load(f)
          assert '@context' in data and '@type' in data and '@id' in data
          assert 'id' in data and 'version' in data and 'owner' in data
          print('JSON-LD structure validation passed')
          "

      - name: Validate against SHACL schema
        run: |
          python scripts/validate_shacl.py examples/policies/healthcare_eligibility.yaml docs/ontology/context.jsonld
