name: Policy Validation

on:
  push:
    branches: [main]
    paths:
      - "policies/**"
      - "schemas/**"
  pull_request:
    branches: [main]
    paths:
      - "policies/**"
      - "schemas/**"

jobs:
  policy-validation:
    name: Policy Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml

      - name: Validate YAML policies
        run: |
          python scripts/validate_policies.py

      - name: Check Rego metadata
        run: |
          python scripts/check_rego_metadata.py

  opa-testing:
    name: OPA Policy Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA tests
        run: |
          find policies/rego -name "*.rego" -exec dirname {} \; | sort -u | while read dir; do
            echo "Testing policy in $dir"
            opa test "$dir" --coverage --threshold 70
          done
